### ISSUE TITLE
Maybe this project is really "Pass for macOS"?

### ISSUE THREAD

**Issue by rnkn** [adur1990/Passafari#20]
Thank you very much for making this project. My search for a macOS interface to `pass` had eventually lead me to switching to Firefox, but upon finding your project I'm very happy back on Safari in a system that feels minimal and unified :)

This issue is more a comment than feature request per se, but given the necessity of the (quite useful) persistent system-wide menu bar icon, maybe your project is really more "Pass for macOS, which happens to include a Safari extension" than it is a mere Safari extension? I think there is [a real desire for this](https://github.com/mssun/passforios/issues/276), and this is essentially what you have already made, albeit with a name that doesn't really imply that. Maybe you could take this unoccupied title?

- Passafari 0.5
- macOS 10.15.2 (19C57)

**Comment by adur1990** [comment]
Hi.

Thank you for your contribution :)

I see your point here. The reason, why this is called Passafari, is because it started as a pure Safari App Extension only.
But over the time, I changed some internals, including removing the App Sandbox from the host app (with the sandbox, the user had to give Passafari the private key, which always felt wrong). But with the new design, the host app was completely useless, but it is (as you state) mandatory since Safari 12. So, following user suggestion (you can follow the conversation [here](https://github.com/adur1990/Passafari/issues/16)), I implemented the current behavior.

So, that's about history.
The problem I have with your suggestion is that it implies, that this app is a standalone macOS pass app or kind of a reimplementation of pass for macOS (ass [passforios](https://github.com/mssun/passforios) does for iOS), not an app, which interacts with your existing pass setup. But as I said, I totally see your point. Maybe am I just overcomplicating the problem? Maybe it would be sufficient to state in the readme, that you have to have a working pass installation?
I also want to have the regular pass installation available because I'm about 50% of my time using a terminal, so accessing pass over the CLI is also something I do not want to lose. So, reimplementing it using Swift and having the original pass installed feels somewhat overcomplicated?

So, generally, I'm for renaming the project. Maybe we can come up with some more options? But again, maybe I'm just overthinking it. What do you say?

**Comment by rnkn** [comment]
That is a good point. I had just assumed everyone has the pass CLI installed and anything else is in addition to that.

I like the way you have it as just an interaction with pass. It feels cleaner and more minimal. More Unix-like. The way you have the README now seemed like that’s how it worked, but maybe a “Requirements” section would allay your concerns?

**Comment by adur1990** [comment]
Okay, you got me. So, I will rename the project to "Pass for macOS", make it clear in the readme that pass is required and make pass a dependency when installing using homebrew. Give me some days to do this.

I would like to mention you in the readme as a contributor if you are fine with this.

**Comment by rnkn** [comment]
Oh you flatter me. Sure, whatever you think is best.
